# Setup
title:        nemozqqz's blog
tagline:      不要去当流水线工人，而是去创造一套新的流水线
baseurl:      ""
paginate:     1
locale:       "en"

github:
    url: https://nemozqqz.github.io

author:
  name:       nemozqqz
  url:        https://nemozqqz.github.io 

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate

#Others
markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  input: GFM

