# Setup
title:        nemozqqz's blog
tagline:      不要去当流水线工人，而是去创造一套新的流水线
baseurl:      ""
paginate:     1
locale:       "en"

author:
  name:       nemozqqz
  url:        https://nemozqqz.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
